### PR TITLE
Use navTo to forward route info for the nested components

### PR DESCRIPTION
**Pull request by stopcoder**
- since UI5 version 1.72, the navTo method is enhanced with a
  third parameter to give route and parameters information to
  the nested components which are loaded by this navTo route.
  This change uses new feature of navTo function to navigate
  to the detail state of a nest component directly.

- The communication between nested and parent component is done
  via eventing so that the nested component can still run
  standalone without knowing the existence of the parent
  component.

- The nightly build of OpenUI5 is used as the bootstrap of
  index.html since 1.72 isn't officially released yet. The
  bootstrap can be reverted once 1.72 is released.

### CODE REVIEW

**Comment by stopcoder** [comment]
Hi @grahamrobbo,

I am Jiawei Cao from UI5 Core Framework development in SAP. My colleague forwarded me your blog post about "Routing with nested components". It's a great and well-written blog post. Thank you for helping us promote this feature.

You mentioned some workaround in the blogpost which is due to the missing functionality to give the route information about the nested components which is also tracked by this [bug report](https://github.com/SAP/openui5/issues/2610). We closed this gap with UI5 version 1.72.

In this pull request, I would like to show how the new signature of `navTo` function can be used for giving information to a nested component when navigating to a route where the nested component is loaded.

Could you please have a look at the pull request?

Best regards,
Jiawei

**Comment by grahamrobbo** [comment]
Sorry I missed this mate - a bit frantic here at the moment with bushfires all around. I'll get to this as soon as I can. I just need to revisit my blog post to ensure I can still refer to the original code until v 1.72 is released.

**Comment by stopcoder** [comment]
With the second commit of this pull request, I replaced the product table in both Supplier and Category detail page with the products component in order to get a feeling about how complex it is to have a deeply nested component and maximize the reusability of a component.

The code doesn't work as expected yet because we found a bug in 1.72 regarding the new feature in `navTo` method. The fix of the bug is ongoing and should be merged today. The nightly build should have the fix included from tomorrow and you can then test the second commit.

**Comment by stopcoder** [comment]
Hi @grahamrobbo,

the fix I mentioned yesterday is already available in openui5 nightly build. You can have a try with this pull request.

Best regards,
Jiawei

**Review by grahamrobbo — APPROVED** [review]
Awesome stuff mate - I have made you an admin of this repo so my tardiness doesn't continually hold you up.

**Comment by grahamrobbo** [comment]
This stuff will need to be carefully documented. Extra coolness means extra complexity too. 😎

**Pull request merged**
